// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goApiByGin/ent/predicate"
	"goApiByGin/ent/token"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TokenUpdate is the builder for updating Token entities.
type TokenUpdate struct {
	config
	hooks    []Hook
	mutation *TokenMutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (tu *TokenUpdate) Where(ps ...predicate.Token) *TokenUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUser sets the "user" field.
func (tu *TokenUpdate) SetUser(u uuid.UUID) *TokenUpdate {
	tu.mutation.SetUser(u)
	return tu
}

// SetToken sets the "token" field.
func (tu *TokenUpdate) SetToken(s string) *TokenUpdate {
	tu.mutation.SetToken(s)
	return tu
}

// SetRefreshToken sets the "refresh_token" field.
func (tu *TokenUpdate) SetRefreshToken(s string) *TokenUpdate {
	tu.mutation.SetRefreshToken(s)
	return tu
}

// SetSecret sets the "secret" field.
func (tu *TokenUpdate) SetSecret(s string) *TokenUpdate {
	tu.mutation.SetSecret(s)
	return tu
}

// SetDevice sets the "device" field.
func (tu *TokenUpdate) SetDevice(s string) *TokenUpdate {
	tu.mutation.SetDevice(s)
	return tu
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableDevice(s *string) *TokenUpdate {
	if s != nil {
		tu.SetDevice(*s)
	}
	return tu
}

// ClearDevice clears the value of the "device" field.
func (tu *TokenUpdate) ClearDevice() *TokenUpdate {
	tu.mutation.ClearDevice()
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TokenUpdate) SetCreatedAt(t time.Time) *TokenUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableCreatedAt(t *time.Time) *TokenUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TokenUpdate) SetUpdatedAt(t time.Time) *TokenUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableUpdatedAt(t *time.Time) *TokenUpdate {
	if t != nil {
		tu.SetUpdatedAt(*t)
	}
	return tu
}

// SetIP sets the "ip" field.
func (tu *TokenUpdate) SetIP(s string) *TokenUpdate {
	tu.mutation.SetIP(s)
	return tu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableIP(s *string) *TokenUpdate {
	if s != nil {
		tu.SetIP(*s)
	}
	return tu
}

// ClearIP clears the value of the "ip" field.
func (tu *TokenUpdate) ClearIP() *TokenUpdate {
	tu.mutation.ClearIP()
	return tu
}

// Mutation returns the TokenMutation object of the builder.
func (tu *TokenUpdate) Mutation() *TokenMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TokenUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TokenUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TokenUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TokenUpdate) check() error {
	if v, ok := tu.mutation.Token(); ok {
		if err := token.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Token.token": %w`, err)}
		}
	}
	if v, ok := tu.mutation.RefreshToken(); ok {
		if err := token.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "Token.refresh_token": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Secret(); ok {
		if err := token.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "Token.secret": %w`, err)}
		}
	}
	return nil
}

func (tu *TokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.User(); ok {
		_spec.SetField(token.FieldUser, field.TypeUUID, value)
	}
	if value, ok := tu.mutation.Token(); ok {
		_spec.SetField(token.FieldToken, field.TypeString, value)
	}
	if value, ok := tu.mutation.RefreshToken(); ok {
		_spec.SetField(token.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := tu.mutation.Secret(); ok {
		_spec.SetField(token.FieldSecret, field.TypeString, value)
	}
	if value, ok := tu.mutation.Device(); ok {
		_spec.SetField(token.FieldDevice, field.TypeString, value)
	}
	if tu.mutation.DeviceCleared() {
		_spec.ClearField(token.FieldDevice, field.TypeString)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(token.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.IP(); ok {
		_spec.SetField(token.FieldIP, field.TypeString, value)
	}
	if tu.mutation.IPCleared() {
		_spec.ClearField(token.FieldIP, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TokenUpdateOne is the builder for updating a single Token entity.
type TokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenMutation
}

// SetUser sets the "user" field.
func (tuo *TokenUpdateOne) SetUser(u uuid.UUID) *TokenUpdateOne {
	tuo.mutation.SetUser(u)
	return tuo
}

// SetToken sets the "token" field.
func (tuo *TokenUpdateOne) SetToken(s string) *TokenUpdateOne {
	tuo.mutation.SetToken(s)
	return tuo
}

// SetRefreshToken sets the "refresh_token" field.
func (tuo *TokenUpdateOne) SetRefreshToken(s string) *TokenUpdateOne {
	tuo.mutation.SetRefreshToken(s)
	return tuo
}

// SetSecret sets the "secret" field.
func (tuo *TokenUpdateOne) SetSecret(s string) *TokenUpdateOne {
	tuo.mutation.SetSecret(s)
	return tuo
}

// SetDevice sets the "device" field.
func (tuo *TokenUpdateOne) SetDevice(s string) *TokenUpdateOne {
	tuo.mutation.SetDevice(s)
	return tuo
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableDevice(s *string) *TokenUpdateOne {
	if s != nil {
		tuo.SetDevice(*s)
	}
	return tuo
}

// ClearDevice clears the value of the "device" field.
func (tuo *TokenUpdateOne) ClearDevice() *TokenUpdateOne {
	tuo.mutation.ClearDevice()
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TokenUpdateOne) SetCreatedAt(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableCreatedAt(t *time.Time) *TokenUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TokenUpdateOne) SetUpdatedAt(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableUpdatedAt(t *time.Time) *TokenUpdateOne {
	if t != nil {
		tuo.SetUpdatedAt(*t)
	}
	return tuo
}

// SetIP sets the "ip" field.
func (tuo *TokenUpdateOne) SetIP(s string) *TokenUpdateOne {
	tuo.mutation.SetIP(s)
	return tuo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableIP(s *string) *TokenUpdateOne {
	if s != nil {
		tuo.SetIP(*s)
	}
	return tuo
}

// ClearIP clears the value of the "ip" field.
func (tuo *TokenUpdateOne) ClearIP() *TokenUpdateOne {
	tuo.mutation.ClearIP()
	return tuo
}

// Mutation returns the TokenMutation object of the builder.
func (tuo *TokenUpdateOne) Mutation() *TokenMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (tuo *TokenUpdateOne) Where(ps ...predicate.Token) *TokenUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TokenUpdateOne) Select(field string, fields ...string) *TokenUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Token entity.
func (tuo *TokenUpdateOne) Save(ctx context.Context) (*Token, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TokenUpdateOne) SaveX(ctx context.Context) *Token {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TokenUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TokenUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TokenUpdateOne) check() error {
	if v, ok := tuo.mutation.Token(); ok {
		if err := token.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Token.token": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.RefreshToken(); ok {
		if err := token.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "Token.refresh_token": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Secret(); ok {
		if err := token.SecretValidator(v); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "Token.secret": %w`, err)}
		}
	}
	return nil
}

func (tuo *TokenUpdateOne) sqlSave(ctx context.Context) (_node *Token, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Token.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, token.FieldID)
		for _, f := range fields {
			if !token.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != token.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.User(); ok {
		_spec.SetField(token.FieldUser, field.TypeUUID, value)
	}
	if value, ok := tuo.mutation.Token(); ok {
		_spec.SetField(token.FieldToken, field.TypeString, value)
	}
	if value, ok := tuo.mutation.RefreshToken(); ok {
		_spec.SetField(token.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Secret(); ok {
		_spec.SetField(token.FieldSecret, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Device(); ok {
		_spec.SetField(token.FieldDevice, field.TypeString, value)
	}
	if tuo.mutation.DeviceCleared() {
		_spec.ClearField(token.FieldDevice, field.TypeString)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(token.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.IP(); ok {
		_spec.SetField(token.FieldIP, field.TypeString, value)
	}
	if tuo.mutation.IPCleared() {
		_spec.ClearField(token.FieldIP, field.TypeString)
	}
	_node = &Token{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
